ci:
  - ./.github/workflows/*
  - ./.github/*
  - .circleci/*
  - .travis.yml
repo:
  - ./*
back:
  - liste-envies-war/src/*
  - liste-envies-war/src/**/*
front:
  - liste-envies-front/src/*
  - liste-envies-front/src/**/*
style:
  - liste-envies-front/**/*.scss
  - liste-envies-front/**/*.css
test:
  - liste-envies-front/**/*.spec.ts
  - liste-envies-war/src/test/**/*.java
dependencies:
  - liste-envies-front/package.json
  - liste-envies-war/pom.xml
