name: Supression d'une branche

on: [delete]

jobs:
  removeversion:
    name: Suppression d'une branche
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "275.0.0"
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      - run: echo Delete branch ${{ github.event.ref }}
      - run: |
          echo Delete branch ${{ github.event.ref }}
          REF=${{ github.event.ref }}
          BRANCH=${REF//[^a-zA-Z0-9]/-}
          APP_VERSION=${BRANCH:0:63};
          echo Delete version ${APP_VERSION}
          gcloud app versions delete --project test-liste-envies ${{ github.event.ref }}
