name: Add url on PR

on: [pull_request]

jobs:
  commentpr:
    runs-on: [ubuntu-latest]
    steps:
      - name: "Wait for status checks"
        id: waitforstatuschecks
        uses: "WyriHaximus/github-action-wait-for-status@f8bbe3bb321919ec6a009bc98121f39874dc8ee0"
        with:
          ignoreActions: commentpr
          checkInterval: 13
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - uses: rlespinasse/github-slug-action@v2.x
      - uses: mshick/add-pr-comment@v1
        if: steps.waitforstatuschecks.outputs.status == 'success'
        with:
          message: |
            Application deployé sur https://${{ env.GITHUB_HEAD_REF_SLUG }}-dot-test-liste-envies.appspot.com/ (http://${{ env.GITHUB_HEAD_REF_SLUG }}.test-liste-envies.appspot.com/)
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          allow-repeats: false
      - name: Slack notification
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_AVATAR: repository # Optional. can be (repository, sender, an URL) (defaults to webhook app avatar)
        uses: Ilshidur/action-slack@master
        with:
          args: "Voir l'application deployé sur https://{{ GITHUB_HEAD_REF_SLUG }}-dot-test-liste-envies.appspot.com/"
